language: r
dist: xenial

cache:
  packages: yes

r_packages:
  - testthat
  - roxygen2
  - covr

addons:
  apt:
    packages:
      - gdal-bin
      - libgdal-dev
      - libproj-dev
      - libgeos-dev
      - r-cran-ncdf4
      - libv8-3.14-dev
      - libprotobuf-dev
      - protobuf-compiler
      - libudunits2-dev
      - libnetcdf-dev
      - libjq-dev

install:
  - wget http://download.osgeo.org/proj/proj-6.0.0.tar.gz
  - tar -xzvf proj-6.0.0.tar.gz
  - cd proj-6.0.0 && ./configure && make && sudo make install && cd ..

after_success:
  - Rscript -e 'covr::coveralls()'
