language: r
dist: xenial

r_packages:
  - devtools
  - testthat
  - roxygen2
  - covr

addons:
  apt:
    packages:
      - gdal-bin
      - libgdal-dev
      - libproj-dev
      - libgeos-dev
      - r-cran-ncdf4
      - libv8-3.14-dev
      - libprotobuf-dev
      - protobuf-compiler
      - libudunits2-dev
      - libnetcdf-dev
      - libjq-dev

before_install:
  - Rscript -e 'install.packages("sp")'
  - Rscript -e 'install.packages("rgdal", repos="http://R-Forge.R-project.org")'

after_success:
  - Rscript -e 'covr::coveralls()'
